# Generated by Django 4.2.5 on 2023-12-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='status',
        ),
        migrations.AddField(
            model_name='tbl_user',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
