# Generated by Django 4.2.5 on 2024-04-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0002_remove_medicalhistory_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
