# Generated by Django 4.2.5 on 2023-12-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0002_remove_doctor_status_tbl_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
