# Generated by Django 4.2.5 on 2024-02-27 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0002_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmenttime',
            name='time_from',
        ),
        migrations.RemoveField(
            model_name='appointmenttime',
            name='time_to',
        ),
    ]
