# Generated by Django 4.2.5 on 2023-12-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0003_tbl_user_email_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consulting_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
