# Generated by Django 4.2.5 on 2024-02-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0003_remove_appointmenttime_time_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_image',
            field=models.ImageField(default='default.png', upload_to='doctor/'),
        ),
    ]
