# Generated by Django 4.2.5 on 2023-10-08 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0003_tbl_user_user_type_alter_tbl_user_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=100)),
                ('consultancy_fees', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('user_status', models.CharField(max_length=50)),
                ('login_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('spec_id', models.AutoField(primary_key=True, serialize=False)),
                ('spec_name', models.CharField(max_length=100)),
                ('spec_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_contno', models.IntegerField()),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_gender', models.CharField(max_length=6)),
                ('patient_add', models.TextField()),
                ('patient_age', models.IntegerField()),
                ('patient_medhis', models.TextField()),
                ('creation_date', models.DateTimeField()),
                ('updation_date', models.DateTimeField()),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medi.doctor')),
                ('login_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='spec_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medi.specialty'),
        ),
    ]
