# Generated by Django 4.2.5 on 2024-02-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0004_alter_patient_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_image',
            field=models.ImageField(default='patient8.jpg', upload_to='doctor/'),
        ),
    ]
