# Generated by Django 4.2.5 on 2023-12-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0004_doctor_consulting_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='consulting_fee',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
