# Generated by Django 4.2.5 on 2023-10-08 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0004_doctor_specialty_patient_doctor_spec_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor',
            new_name='tbl_doctor',
        ),
        migrations.RenameModel(
            old_name='Patient',
            new_name='tbl_patient',
        ),
        migrations.RenameModel(
            old_name='Specialty',
            new_name='tbl_specialty',
        ),
    ]
