# Generated by Django 4.2.5 on 2024-04-17 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0004_medicaldata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionnaireResponse',
        ),
        migrations.AddField(
            model_name='appointment',
            name='medical_data_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='appointment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='medi.appointment'),
        ),
    ]
