# Generated by Django 4.2.5 on 2024-03-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0005_appointment_appointment_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=20)),
                ('height', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
            ],
        ),
    ]
