# Generated by Django 4.2.5 on 2023-11-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0005_patient_address_alter_patient_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pin',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
