# Generated by Django 4.2.5 on 2023-12-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0005_alter_doctor_consulting_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='consulting_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
