# Generated by Django 4.2.5 on 2023-10-08 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0005_rename_doctor_tbl_doctor_rename_patient_tbl_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_doctor',
            name='login_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tbl_patient',
            name='login_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
