# Generated by Django 4.2.5 on 2024-04-18 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0005_delete_questionnaireresponse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionstatus',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='prescriptionstatus',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='PrescriptionStatus',
        ),
    ]
