# Generated by Django 4.2.5 on 2024-03-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0006_questionnaireresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_datetime',
            field=models.DateField(null=True),
        ),
    ]
