# Generated by Django 4.2.5 on 2023-10-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0006_alter_tbl_doctor_login_id_alter_tbl_patient_login_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_doctor',
            name='spec_id',
        ),
        migrations.RemoveField(
            model_name='tbl_patient',
            name='doc_id',
        ),
        migrations.AlterField(
            model_name='tbl_doctor',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_doctor',
            name='consultancy_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_doctor',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_doctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_doctor',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_doctor',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_doctor',
            name='user_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_patient',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_patient',
            name='patient_add',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_patient',
            name='patient_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_patient',
            name='patient_contno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_patient',
            name='patient_gender',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_patient',
            name='patient_medhis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_patient',
            name='updation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
