# Generated by Django 4.2.5 on 2023-11-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0006_patient_pin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='user',
            new_name='doctor',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
