# Generated by Django 4.2.5 on 2024-04-18 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0006_remove_prescriptionstatus_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('intake_time', models.CharField(choices=[('0-0-1', '0-0-1'), ('1-1-1', '1-1-1'), ('1-0-0', '1-0-0'), ('0-1-0', '0-1-0'), ('1-1-0', '1-1-0'), ('1-0-1', '1-0-1')], max_length=10)),
                ('days', models.PositiveIntegerField()),
                ('prescription_added_date', models.DateTimeField(auto_now_add=True)),
                ('prescription_text', models.TextField(blank=True)),
                ('is_uploaded', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medi.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medi.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medi.patient')),
            ],
        ),
    ]
