# Generated by Django 4.2.5 on 2024-04-18 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0007_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medi.appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
