# Generated by Django 4.2.5 on 2023-10-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0007_remove_tbl_doctor_spec_id_remove_tbl_patient_doc_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_doctor',
            name='login_id',
        ),
        migrations.RemoveField(
            model_name='tbl_patient',
            name='login_id',
        ),
    ]
