# Generated by Django 4.2.5 on 2024-02-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0008_alter_doctor_consulting_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='consulting_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
