# Generated by Django 4.2.5 on 2024-02-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0009_alter_doctor_consulting_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
