# Generated by Django 4.2.5 on 2024-04-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0009_appointment_appointment_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttime',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
