# Generated by Django 4.2.5 on 2024-02-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0011_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_datetime',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
