# Generated by Django 4.2.5 on 2024-02-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0012_alter_appointment_appointment_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='consulting_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
