# Generated by Django 4.2.5 on 2024-02-20 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0014_appointment_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='slot',
        ),
    ]
